server:
  internalPort: 8008
  externalPort: 8008
  runMode: debug
cors:
  allowOrigins: "*"
postgres:
  host: ep-polished-wind-a7q9wvj3.ap-southeast-2.aws.neon.tech
  port: 5432
  user: default
  password: "postgresPassword"
  dbName: verceldb
  sslMode: require
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60
